# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: BLOG-PUBLISH 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    #因为要对比需要更新的文件所以fetch-depth为0
    - name: 迁出main
      uses: actions/checkout@v2
      with: 
        path: main
        fetch-depth: 0

    - name: 安装 .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    
    - name: 下载发布工具
      run : |
        wget -c https://github.com/zhepama/ABPHass/releases/download/v1.1.5/blog-publishtool.tar.gz
        tar -zxvf blog-publishtool.tar.gz
        ls -al

    - name: 发布
      run : |
        dotnet ./blogpublishtool/DotHass.Blog.PublishTool.dll -f $GITHUB_WORKSPACE/main -m 1 --uri "http://www.godgodgame.com" --pwd ${{ secrets.BLOG_PWD }} --id Www_App --count 10 --img "https://cdn.jsdelivr.net/gh/zhepama/igiven.github.io@gh-pages"
  

      
